### PR TITLE
Django 1.9 and Python 3.5 support

### PR DESCRIPTION
**Pull request by raphaelmerx**
This is building up on your django-19 branch @vkurup. I removed all the deprecation warnings, apart from the one thrown in django-selectable. I'm working on fixing that deprecation warning in the django-selectable repository. Also dropped support for Django 1.7 and Python 3.3, added support for Python 3.5.

In summary:
* Added support for Python 3.5, Django 1.9
* Removed support for Python 3.3, Django 1.6, Django 1.7
* Fixed the build by pinning the django-tables2 version to 1.0.*

### CODE REVIEW

**Comment by vkurup** [comment]
Thank you! I haven't had time to work on RapidSMS recently so this is much-appreciated. The only change is that this should be against the `develop` branch. We only use master when we cut a release.

**Comment by raphaelmerx** [comment]
No problem @vkurup, thank you for all your work on RapidSMS. We use it for Liga Inan to send about 1,000 messages every day.

**Comment by raphaelmerx** [comment]
ping @vkurup, let me know if there are other changes I should put in

**Comment by vkurup** [comment]
Sorry, I missed the Github notification. Thanks again for your contribution. It is great to hear that it is so useful to you!

**Comment by hugovk** [comment]
Don't forget to update the classifiers: https://github.com/rapidsms/rapidsms/blob/develop/setup.py#L45-L49

'Programming Language :: Python :: 2' would be useful too.

You could also add support for 3.6.

**Comment by vkurup** [comment]
@hugovk thanks for the reminder. I've now updated them. https://pypi.python.org/pypi/RapidSMS/0.22.0 I didn't have time to get Python3.6 working in Travis yet...

**Pull request merged**
