### PR TITLE
Django 1.8 support

### PR DESCRIPTION
**Pull request by vkurup**
This PR provides support for the master branch of Django (which will become 1.8 once released). I've combined a few different fixes in with this because they were generally reliant on each other.

Backwards incompatibility: This drops support for Django 1.4 and 1.5. This makes it possible to use `transaction.atomic`, allow using the `url` templatetag without importing it from future, and allows us to use the latest version of Celery.

Needed after this PR is merged: Documentation updates, especially for the switch from django-celery to plain old Celery. (Added to my todo list)

This PR is done on top of #452 and I'll update it once that one is approved.

### CODE REVIEW

**Comment by dpoirier** [comment]
I'm seeing test failures on py27-trunk and flake8.

On py27-trunk, it looks like django-tables2 is not compatible with Django trunk:

      File "/home/dpoirier/caktus/rapidsms/.tox/py27-trunk/local/lib/python2.7/site-packages/django
    _tables2/columns/base.py", line 4, in <module>
        from django.utils.datastructures import SortedDict
    ImportError: cannot import name SortedDict

flake8 finds all sorts of problems. Maybe we should use another issue to fix those, though.

**Comment by vkurup** [comment]
Which Travis build has the flake8 failures? This is the one for this PR: https://travis-ci.org/rapidsms/rapidsms/jobs/47585276

py27-trunk is going to fail because Django cut a 1.8 alpha release, so the trunk is now Django 1.9 (which I have not addressed at all).

py27-1.8.X is the new environment I created for the 1.8 branch.

**Comment by dpoirier** [comment]
I saw those failures when I ran "tox" locally.

**Comment by vkurup** [comment]
Ahh, ok. If you can post them, I can fix them here, or in a separate issue. tox succeeds locally for me. It might be getting confused with a local setup.cfg file?

**Comment by thedrow** [comment]
@vkurup This PR should be rebased.

**Comment by vkurup** [comment]
Actually, this can be closed. All of the changes from this PR were included in #454.

**Comment by thedrow** [comment]
Cool :)

**Pull request closed without merging**
