### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by vkurup**
Mostly minor fixes to provide Python 3 support. This is built on top of #453.

Will probably also need doc updates, but wanted to get this out there for review in the meantime.

### CODE REVIEW

**Comment by dpoirier** [comment]
Github seems to be showing a whole lot more commits in this pull than I think were intended to be part of it?

**Comment by vkurup** [comment]
Yes, this is built on top of #453. Only the last commit is for Python3 support.

**Comment by mlavin** [comment]
This is awesome. The `setup.py` should probably also be updated with Python 3 related classifiers: https://github.com/rapidsms/rapidsms/blob/develop/setup.py#L49. Is 2.6 still supported?

**Comment by vkurup** [comment]
Thanks, Mark! Python 2.6 is still supported, but only with Django 1.6, since that's what's included in the Django compatibility page: https://docs.djangoproject.com/en/1.7/faq/install/#what-python-version-can-i-use-with-django

**Comment by lsgunth** [comment]
I've got a new server with Django 1.8 and python 3.2 running this code. It's so far working well (with the couple pull requests I've issued). Please release it as soon as you can. 

Thanks,

Logan

**Comment by vkurup** [comment]
Any other comments on this PR? If not, I'll plan to merge in about a week or so, since I know it's gotten a decent bit of review already, and seems to be working. Thanks!

**Comment by thedrow** [comment]
@vkurup If you don't mind please release a new version after merging this.
We're upgrading to Python 3 soon and we'd love to keep RapidSMS in our infrastructure.

**Comment by vkurup** [comment]
Sorry for the delay on this. I'll work on getting a release out.

**Pull request merged**
